# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 11:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('node_hierarchy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/attachment', verbose_name='Attachment')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Reject'), (1, 'Approve'), (2, 'Pending')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ManyToManyField(blank=True, related_name='message_attachments_rel', to='message.Attachment')),
                ('send_to', models.ManyToManyField(related_name='message_nodes_rel', to='node_hierarchy.NodeHierarchy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_user_rel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.BooleanField(default=False)),
                ('like', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_message_rel', to='message.Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_user_rel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
