# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node_hierarchy', '0002_auto_20160430_1220'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Reject'), (1, 'Approve'), (2, 'Pending')], default=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='send_to',
        ),
        migrations.RemoveField(
            model_name='message',
            name='status',
        ),
        migrations.AddField(
            model_name='messagedelivery',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_delivery_rel', to='message.Message'),
        ),
        migrations.AddField(
            model_name='messagedelivery',
            name='send_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_nodes_rel', to='node_hierarchy.NodeHierarchy'),
        ),
    ]
