# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_auto_20160506_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file_type',
            field=models.IntegerField(choices=[(0, 'IMAGE'), (1, 'VIDEO'), (2, 'AUDIO'), (3, 'DOC')], default=0),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=b'attachments', verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='messagedelivery',
            name='status',
            field=models.IntegerField(choices=[(0, 'Rejected'), (1, 'Approved'), (2, 'Pending')], default=2),
        ),
    ]
