# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_auto_20160513_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='messagedelivery',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='socialicon',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='messagedelivery',
            name='send_user_role',
            field=models.IntegerField(choices=[(0, 'User'), (1, 'Staff'), (2, 'All')], default=2),
        ),
    ]
