# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_auto_20160609_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagedelivery',
            name='send_user_role',
        ),
        migrations.AddField(
            model_name='message',
            name='send_user_role',
            field=models.IntegerField(choices=[(3, 'Staff'), (4, 'User'), (5, 'All')], default=5),
        ),
    ]
