# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 10:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0011_auto_20160618_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 21, 10, 36, 3, 776000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialicon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 21, 10, 36, 12, 284000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
