# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeHierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='State/District/Taluko/Village name', max_length=25)),
                ('node_type', models.IntegerField(choices=[(0, 'State'), (1, 'District'), (2, 'Taluko'), (3, 'Village/City')], default=3)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_rel', to='node_hierarchy.NodeHierarchy')),
            ],
        ),
    ]
