# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodehierarchy',
            name='name',
            field=models.CharField(help_text='State/District/Taluko/Village name', max_length=50),
        ),
    ]
