# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node_hierarchy', '0002_auto_20160430_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nodehierarchy',
            options={'ordering': ('name',)},
        ),
    ]
