# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configure', models.IntegerField(choices=[(0, 'IMAGE'), (1, 'VIDEO'), (2, 'AUDIO'), (3, 'DOC')], unique=True)),
                ('maximum_attachment', models.IntegerField(help_text='How many attachments allowed in one message.')),
                ('maximum_attachment_size', models.IntegerField(help_text='Enter size, how much size attachment allowed in one message')),
                ('extension_allow', models.CharField(help_text='enter value comma separate.', max_length=200)),
            ],
        ),
    ]
