# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='maximum_attachment_size',
            field=models.IntegerField(help_text='Enter size in MB, how much size attachment allowed in one message'),
        ),
    ]
