# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0002_auto_20160503_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='extension_allow',
            field=models.CharField(default='ALL', help_text="enter value comma separate(if value is 'ALL' then allow all formats).", max_length=200),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='maximum_attachment_size',
            field=models.IntegerField(help_text="Enter size in MB, how much attachment's size allowed in one message"),
        ),
    ]
