# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0003_auto_20160504_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='extension_allow',
            field=models.CharField(default='ALL', help_text='enter value comma separate.', max_length=200),
        ),
    ]
