# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='designation',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
