# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_userextend_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='contact_num',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
