# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20160502_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='android_device_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
