# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 06:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0004_userextend_android_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordConfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_confirm_rel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
