# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 05:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_passwordconfirm_expired_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextend',
            name='department',
        ),
        migrations.AlterField(
            model_name='passwordconfirm',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 7, 11, 15, 34, 146000)),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
