# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 07:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_auto_20160506_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordconfirm',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 7, 12, 30, 4, 779000)),
        ),
    ]
