# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 10:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20160506_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identitytype',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='passwordconfirm',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='userextend',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='userextend',
            name='android_device_id',
        ),
        migrations.AlterField(
            model_name='passwordconfirm',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 14, 16, 21, 16, 501000)),
        ),
    ]
